src/Entity/Campaign.php
<?php

namespace App\Entity;

use App\Repository\CampaignRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CampaignRepository::class)]
class Campaign
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 150)]
    private ?string $title = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $content = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $created_At = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $updated_At = null;

    #[ORM\Column]
    private ?int $goal = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\OneToMany(mappedBy: 'Campaign', targetEntity: Participant::class, orphanRemoval: true)]
    private Collection $participants;

    public function __construct()
    {
        $this->participants = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(?string $title): static
    {
        $this->title = $title;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(?string $content): static
    {
        $this->content = $content;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_At;
    }

    public function setCreatedAt(?\DateTimeImmutable $created_At): static
    {
        $this->created_At = $created_At;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updated_At;
    }

    public function setUpdatedAt(?\DateTimeImmutable $updated_At): static
    {
        $this->updated_At = $updated_At;

        return $this;
    }

    public function getGoal(): ?int
    {
        return $this->goal;
    }

    public function setGoal(?int $goal): static
    {
        $this->goal = $goal;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    /**
     * @return Collection<int, Participant>
     */
    public function getParticipants(): Collection
    {
        return $this->participants;
    }

    public function addParticipant(Participant $participant): static
    {
        if (!$this->participants->contains($participant)) {
            $this->participants->add($participant);
            $participant->setCampaign($this);
        }

        return $this;
    }

    public function removeParticipant(Participant $participant): static
    {
        if ($this->participants->removeElement($participant)) {
            // set the owning side to null (unless already changed)
            if ($participant->getCampaign() === $this) {
                $participant->setCampaign(null);
            }
        }

        return $this;
    }
}

src/Form/CampaignType.php
<?php

namespace App\Form;

use App\Entity\Campaign;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CampaignType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('title', TextareaType::class, [
                'label' => 'Titre de votre campagne',
                'label_attr' => [
                    'class' => 'input-field col s12 l8'
                ],
            ])

            ->add('content', TextareaType::class, [
                'label' => 'Décrivez à vos amis pourquoi vous faites une campagne',
                'label_attr' => [
                    'class' => 'input-field col s12'
                ],
            ])
            // ->add('created_At')
            // ->add('updated_At')
            ->add('goal', NumberType::class, [
                'label' => 'Votre objectif en euros',
                'label_attr' => [
                    'class' => 'input-field col s12 l6'
                ],
            ])
            ->add('name', TextType::class, [
                'label' => 'Votre Nom',
                'label_attr' => [
                    'class' => 'input-field col s12 l6'
                ],
            ]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Campaign::class,
        ]);
    }
}

src/Controller/CampaignController.php
<?php

namespace App\Controller;

use App\Entity\Campaign;
use App\Form\CampaignType;
use App\Repository\CampaignRepository;
use DateTimeImmutable;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/campaign')]
class CampaignController extends AbstractController
{
    #[Route('/', name: 'app_campaign_index', methods: ['GET'])]
    public function index(CampaignRepository $campaignRepository): Response
    {
        return $this->render('campaign/index.html.twig', [
            'campaigns' => $campaignRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_campaign_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $campaign = new Campaign();
        
        $form = $this->createForm(CampaignType::class, $campaign);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $campaign->setCreatedAt(new DateTimeImmutable());
            $campaign->setUpdatedAt(new DateTimeImmutable());

            $entityManager->persist($campaign);
            $entityManager->flush();

            return $this->redirectToRoute('app_campaign_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('campaign/new.html.twig', [
            'campaign' => $campaign,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_campaign_show', methods: ['GET'])]
    public function show(Campaign $campaign): Response
    {
        return $this->render('campaign/show.html.twig', [
            'campaign' => $campaign,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_campaign_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Campaign $campaign, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(CampaignType::class, $campaign);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_campaign_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('campaign/edit.html.twig', [
            'campaign' => $campaign,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_campaign_delete', methods: ['POST'])]
    public function delete(Request $request, Campaign $campaign, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$campaign->getId(), $request->request->get('_token'))) {
            $entityManager->remove($campaign);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_campaign_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/campaign/_delete_form.html.twig
<form method="post" action="{{ path('app_campaign_delete', {'id': campaign.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ campaign.id) }}">
    <button class="btn">Delete</button>
</form>

templates/campaign/_form.html.twig
{{ form_start(form) }}

{{ form_row(form.name) }}

{{ form_row(form.title) }}

{{ form_row(form.content) }}

{{ form_row(form.goal) }}
<button class="btn btn-large waves-effect waves-light pink lighten-1 col s12" style="margin-top: 20px;" type="submit" name="action">
	Validez la campagne
	<i class="material-icons right">send</i>
</button>
{{ form_end(form) }}

templates/campaign/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Campaign{% endblock %}

{% block body %}
    <h1>Edit Campaign</h1>

    {{ include('campaign/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_campaign_index') }}">back to list</a>

    {{ include('campaign/_delete_form.html.twig') }}
{% endblock %}

templates/campaign/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Campaign index{% endblock %}

{% block body %}
    <h1>Campaign index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Title</th>
                <th>Content</th>
                <th>Created_At</th>
                <th>Updated_At</th>
                <th>Goal</th>
                <th>Name</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for campaign in campaigns %}
            <tr>
                <td>{{ campaign.id }}</td>
                <td>{{ campaign.title }}</td>
                <td>{{ campaign.content }}</td>
                <td>{{ campaign.createdAt ? campaign.createdAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ campaign.updatedAt ? campaign.updatedAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ campaign.goal }}</td>
                <td>{{ campaign.name }}</td>
                <td>
                    <a href="{{ path('app_campaign_show', {'id': campaign.id}) }}">show</a>
                    <a href="{{ path('app_campaign_edit', {'id': campaign.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="8">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_campaign_new') }}">Create new</a>
{% endblock %}

templates/campaign/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Campaign
{% endblock %}
{% block stylesheets %}
	<!--Simple MDE -->
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.css">
{% endblock %}
{% block body %}

    <div class="parallax-container valign-wrapper">
        <div class="section no-pad-bot">
            <div class="container">
                <div class="hide-on-med-and-down">
                    <h1 class="header center white-text light">Un cadeau commun à organiser?</h1>
                    <div class="row center">
                        <h5 class="header col s12 light">Anniversaire, pot de départ, crémaillère... N'avancez plus les frais !</h5>
                    </div>
                </div>
                <div class="hide-on-large-only">
                    <div class="row center">
                        <h5 class="header col s12 light">Un cadeau commun à organiser ?</h5>
                    </div>
                </div>
            </div>
        </div>
        <div class="parallax"><img src="{{ asset('assets/images/11.jpg') }}" alt="Anniversaire, pot de départ, crémaillère... N'avancez plus les frais !"></div>
    </div>

    <div class="container">
        <div class="section">
            <div class="row">
                <div class="col s12 center">
                    <h4>Créez votre campagne maintenant</h4>
                </div>
            </div>
            <!--   Form Section   -->
            <div class="card">
                <div class="card-content">
                    <div class="row">
                        {{include('campaign/_form.html.twig')}}
                    </div>
                </div>
            </div>

        </div>
    </div>

    <div class="container">
        <div class="section">
            <div class="row">
                <div class="col s12 center">
                    <h4>Comment ça marche ?</h4>
                </div>
            </div>
            <!--   Icon Section   -->
            <div class="row">
                <div class="col s12 m4">
                    <div class="icon-block center">
                        <div class="btn-large btn-floating white"><i class="material-icons teal-text">create</i></div>
                        <h5 class="center">Créez</h5>
                        <p class="light">et personnalisez votre campagne commune en 30 secondes !</p>
                    </div>
                </div>

                <div class="col s12 m4">
                    <div class="icon-block center">
                        <div class="btn-large btn-floating white"><i class="material-icons teal-text">wc</i></div>
                        <h5 class="center">Invitez</h5>
                        <p class="light">vos amis en utilisant les réseaux sociaux, mail, etc.</p>
                    </div>
                </div>

                <div class="col s12 m4">
                    <div class="icon-block center">
                        <div class="btn-large btn-floating white"><i class="material-icons teal-text">shopping_cart</i></div>
                        <h5 class="center">Collectez</h5>
                        <p class="light">et utilisez l'argent comme bon vous semble avec vos amis.</p>
                    </div>
                </div>
            </div>

        </div>
    </div>
{% endblock %}
{% block javascripts %}
	<!--Javascript Markdown editor-->
	<script src="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.js"></script>

{% endblock %}

templates/campaign/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Campaign
{% endblock %}

{% block body %}
	<div class="parallax-container valign-wrapper">
		<div class="section no-pad-bot">
			<div class="container">
				<h1 class="header center white-text light">Titre de la campagne</h1>
				<div class="row center">
					<h5 class="header col s12 light">- Organisée par : Nom de l'auteur -</h5>
				</div>
			</div>
		</div>
		<div class="parallax"><img src="{{ asset('assets/images/8.jpg') }}" alt="Titre de la campagne"></div>
	</div>

	<!-- Show progress -->
	<section class="progress-section">
		<div class="progress">
			<div class="determinate" style="width: 70%">
				<span>70% de l'objectif</span>
			</div>
		</div>
	</section>

	<div class="container participe">
		<div
			class="section">
			<!-- Participation section -->
			<div class="row">
				<div class="card col s12 m12 l8 offset-l2">
					<div class="card-content">
						<div class="input-field col s12 l6">
							<input id="mount" type="number" class="validate">
							<label for="mount">Votre participation</label>
						</div>
						<a href="create.html" class="btn-large waves-effect waves-light pink lighten-1 col s12 l6">Participer</a>
						<div class="clearfix"></div>
					</div>
				</div>
			</div>
			<div class="row">
				<div class="col s12 center">
					<h4>A propos de la campagne</h4>
				</div>
			</div>
			<!--   Icon Section   -->
			<div class="row">
				<div class="col s12 m6 l3 offset-l3">
					<div class="icon-block center">
						<div class="btn-large btn-floating white">
							<i class="material-icons teal-text">person</i>
						</div>
						<h3 class="center">12</h3>
						<p class="light">Participants</p>
					</div>
				</div>

				<div class="col s12 m6 l3">
					<div class="icon-block center">
						<div class="btn-large btn-floating white">
							<i class="material-icons teal-text">redeem</i>
						</div>
						<h3 class="center">220</h3>
						<p class="light">euros récoltés</p>
					</div>
				</div>
			</div>
			<!-- Form section -->
			<div class="row">
				<form>
					<div class="input-field col s12">
						<label for="description">Description</label>
						<textarea id="description" class="materialize-textarea" readonly="readonly">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam scelerisque id nunc nec volutpat. Etiam pellentesque tristique arcu, non consequat magna fermentum ac. Cras ut ultricies eros. Maecenas eros justo.</textarea>
					</div>
					<div class="input-field col s12 l6">
						<input id="goal" type="number" readonly="readonly" value="500">
						<label for="goal">Objectif</label>
					</div>
					<div class="col s12 l6 offset-l3">
						<button class="btn btn-large waves-effect waves-light col s12" type="submit" name="action">
							Modifiez la campagne
							<i class="material-icons right">edit</i>
						</button>
					</div>
				</form>
			</div>
		</div>
	</div>
{% endblock %}